/**
 * This application displays documentation generated by the docgen tool
 * found at dart-repo/dart/pkg/docgen. 
 * 
 * The Yaml file outputted by the docgen tool will be read in to 
 * generate [Page] and [Category] and [CompositeContainer]. 
 * Pages, Categories and CategoryItems are used to format and layout the page.
 */
// TODO(janicejl): Add a link to the dart docgen landing page in future. 
library dartdoc_viewer;

import 'dart:async';
import 'dart:html';

import 'package:dartdoc_viewer/data.dart';
import 'package:dartdoc_viewer/item.dart';
import 'package:dartdoc_viewer/read_yaml.dart';
import 'package:web_ui/web_ui.dart';

// TODO(janicejl): YAML path should not be hardcoded. 
// Path to the YAML file being read in. 
const sourcePath = '../../docs/library_list.txt';

/// The [Viewer] object being displayed.
Viewer viewer;

/**
 * The Dartdoc Viewer application state.
 */
class Viewer {
  
  Future finished;

  /// The homepage from which every [Item] can be reached.
  @observable Home homePage;
  
  /// The current page being shown.
  @observable Item currentPage;

  // Private constructor for singleton instantiation.
  Viewer._() {
    var manifest = retrieveFileContents(sourcePath);
    finished = manifest.then((response) {
      var libraries = response.split('\n');
      currentPage = new Home(libraries);
      homePage = currentPage;
      return true;
    });
  }
  
  /// The title of the current page.
  String get title => currentPage == null ? '' : currentPage.decoratedName;
  
  /// Updates the current page.
  void _updatePage(Item page) {
    if (page != null) {
      currentPage = page;
    }
  }
  
  /**
   * Creates a list of [Item] objects from the [path] describing the
   * path to a particular [Item] object.
   */
  List<Item> get breadcrumbs => [homePage]..addAll(currentPage.path);
  
  Item _handleTopLevel(Library library, String topLevel) {
    if (library.classes != null) {
      for (Class clazz in library.classes.content) {
        if (clazz.name == topLevel) return clazz;
      }
    }
    if (library.functions != null) {
      for (Method function in library.functions.content) {
        if (function.name == topLevel) return function;
      }
    }
    // TODO(tmandel): Handle variables somehow.
  }
  
  Item _handleMethod(Class topLevel, String member) {
    int hashIndex = member.indexOf('#');
    
    if (topLevel.functions != null) {
      for (Method function in topLevel.functions.content) {
        if (function.name == member) return function;
      }
    }
    // TODO(tmandel): Handle variables somehow.
  }
  
  Item _findChild(Library library, List members) {
    members.removeWhere((element) => element == '');
    if (members.length > 1) {
      var topLevel = _handleTopLevel(library, members[1]);
      if (topLevel == null) {
        return library;
      } else {
        if (members.length > 2) {
          var method = _handleMethod(topLevel, members[2]);
          if (method == null) {
            return topLevel;
          } else {
            return method;
          }
        } else return topLevel;
      }
    } else return library;
  }
  
  void handleLink(List<String> location) {
    _handleLinkWithoutState(location).then((response) {
      if (response) _updateState(currentPage);
    });
  }
  
  /// Handles lazy loading of libraries from links not on the homepage.                               
  Future _handleLinkWithoutState(List<String> location) {
    if (location != null) {
      var libraryName = location.first;
      if (libraryName == 'home') {
        _updatePage(homePage);
        return new Future.value(true);
      }
      var member = homePage.getMember(libraryName);
      if (member != null) {
        if (member is Placeholder) {
          return homePage.loadLibrary(member).then((response) {
            var library = response;
            if (library != null) {
              var child = _findChild(library, location);
              if (child != null) _updatePage(child);
              return true;
            }
          });
        } else {
          var child = _findChild(member, location);
          if (child != null) {
            _updatePage(child);
            return new Future.value(true);
          }
        }
      }
    }
    return new Future.value(false);
  }
  
  void changePage(Item page) {
    if (page is Placeholder) {
      homePage.loadLibrary(page).then((response) {
        _updatePage(response);
        _updateState(response);
      });
    } else {
      _updatePage(page);
      _updateState(page);
    }
  }
  
  void _updateState(Item page) {
    String url = '#home';
    for (var member in page.path) {
      if (member != null)
        url = url == '#home' ? '#${libraryNames[member.name]}' : 
          '$url/${member.name}';
    }
    window.history.pushState(url, url.replaceAll('/', '->'), url);
  }
}

String location;

void startHistory() {
  window.onPopState.listen((event) {
    location = window.location.hash.replaceFirst('#', '');
    if (viewer.homePage != null) {
      if (location != '') viewer._handleLinkWithoutState(location.split('/'));
      else viewer._handleLinkWithoutState(['home']);
    }
  });
}

// Handles browser navigation.
main() {
  startHistory();
  viewer = new Viewer._();
  viewer.finished.then((_) {
    if (location != null && location != '') {
      viewer._handleLinkWithoutState(location.split('/'));
    }
  });
}























