/**
 * This application displays documentation generated by the docgen tool
 * found at dart-repo/dart/sdk/lib/_internal/docgen/. 
 * 
 * The Yaml file outputted by the docgen tool will be read in to 
 * generate [Page] and [Category] and [CategoryItem]. 
 * Pages, Categories and CategoryItems are used to format and layout the page. 
 */
// TODO(janicejl): Add a link to the dart docgen landing page in future. 
library dartdoc_viewer;

import 'dart:html';
import 'package:web_ui/web_ui.dart';
import 'package:dartdoc_viewer/data.dart';
import 'package:dartdoc_viewer/item.dart';
import 'package:dartdoc_viewer/read_yaml.dart';

// TODO(janicejl): YAML path should not be hardcoded. 
// Path to the Yaml file being read in. 
const sourcePath = "../../test/yaml/large_test.yaml";

//Function to set the title of the current page. 
String get title => currentPage == null ? "" : currentPage.name;

// The current page being shown.
@observable Item currentPage = null;

/**
 * Changes the currentPage to the page of the item clicked.
 */
changePage(Item page) {
  currentPage = page;
}

main() {
  var sourceYaml = getYamlFile(sourcePath);
  sourceYaml.then( (response) {
    currentPage = loadData(response).first;
  });
}
