/**
 * This application displays documentation generated by the docgen tool
 * found at dart-repo/dart/sdk/lib/_internal/docgen/. 
 * 
 * The Yaml file outputted by the docgen tool will be read in to 
 * generate [Page] and [Category] and [CategoryItem]. 
 * Pages, Categories and CategoryItems are used to format and layout the page. 
 */
// TODO(janicejl): Add a link to the dart docgen landing page in future. 
library dartdoc_viewer;

import 'dart:async';
import 'dart:html';
import 'package:web_ui/web_ui.dart';
import 'package:yaml/yaml.dart';
import 'package:dartdoc_viewer/category.dart';
import 'package:dartdoc_viewer/page.dart';

part 'readYaml.dart';
part 'util.dart';

// Path to the Yaml file being read in. 
const sourcePath = "../yaml/largeTest.yaml";

//Map of pages generated from the YAML file. Keys are the title of the pages. 
Map<String, Page> pageIndex = toObservable({});

//Function to set the title of the current page. 
String get title => currentPage == null ? "untitled" : currentPage.name;

// The current page being shown.
@observable Page currentPage = null;

/**
 * Changes the currentPage to the page of the item clicked.
 */
changePage(Page page) {
  currentPage = page;
}

main() {
  var sourceYaml = getYamlFile(sourcePath);
  sourceYaml.then( (response) {
    currentPage = loadData(response).first;
  });
}
